'use client';
import React, { useEffect, useRef, useState, useLayoutEffect } from 'react';
import { Trophy, Shield, Calendar, Star } from 'lucide-react';

interface TournamentBracketProps {
  matches: any[];
  teamNameMap: Record<string, string>;
  teamLogoMap: Record<string, string>;
  sport: string;
}

export default function TournamentBracket({
  matches,
  teamNameMap,
  teamLogoMap,
  sport,
}: TournamentBracketProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svgPaths, setSvgPaths] = useState<Array<{ d: string; active: boolean; hovered: boolean }>>([]);
  const [hoveredMatchId, setHoveredMatchId] = useState<string | null>(null);

  // 1. Filter knockout matches
  const knockoutStages = ['ROUND_OF_16', 'QUARTER', 'SEMI', 'FINAL'];
  const knockoutMatches = matches.filter((m) => knockoutStages.includes(m.stage));

  // If no knockout matches are generated yet
  if (knockoutMatches.length === 0) {
    return (
      <div className="py-20 flex flex-col items-center text-center bg-neutral-950/40 border border-white/5 rounded-2xl p-6 shadow-xl">
        <Trophy size={48} className="text-neutral-800 mb-4" />
        <p className="text-neutral-400 font-bold text-sm">Knockout Bracket Not Active</p>
        <p className="text-neutral-600 text-xs mt-1 max-w-xs leading-relaxed">
          The knockout stage brackets (Quarter Finals, Semi Finals, and Finals) will be displayed here once generated by the organizer.
        </p>
      </div>
    );
  }

  // 2. Group matches by stage and sort by matchNumber
  const stagesPresent = knockoutStages.filter((s) => knockoutMatches.some((m) => m.stage === s));
  const matchesByStage: Record<string, any[]> = {};
  stagesPresent.forEach((stage) => {
    matchesByStage[stage] = knockoutMatches
      .filter((m) => m.stage === stage)
      .sort((a, b) => a.matchNumber - b.matchNumber);
  });

  const finalMatch = matchesByStage['FINAL']?.[0];
  const championId = finalMatch && finalMatch.status === 'COMPLETED' ? finalMatch.winnerId : null;

  const stageLabel: Record<string, string> = {
    ROUND_OF_16: 'Round of 16',
    QUARTER: 'Quarter Finals',
    SEMI: 'Semi Finals',
    FINAL: 'Finals',
  };

  // 3. Coordinate calculation for connector lines
  const updatePaths = () => {
    if (!containerRef.current) return;
    const containerRect = containerRef.current.getBoundingClientRect();
    const paths: Array<{ d: string; active: boolean; hovered: boolean }> = [];

    // Draw lines between consecutive stages
    for (let sIndex = 0; sIndex < stagesPresent.length - 1; sIndex++) {
      const currentStage = stagesPresent[sIndex];
      const nextStage = stagesPresent[sIndex + 1];

      const currentMatches = matchesByStage[currentStage] || [];
      const nextMatches = matchesByStage[nextStage] || [];

      currentMatches.forEach((match, cIndex) => {
        const targetIndex = Math.floor(cIndex / 2);
        const targetMatch = nextMatches[targetIndex];

        if (targetMatch) {
          const sourceEl = containerRef.current?.querySelector(`#match-card-${match.id}`);
          const destEl = containerRef.current?.querySelector(`#match-card-${targetMatch.id}`);

          if (sourceEl && destEl) {
            const srcRect = sourceEl.getBoundingClientRect();
            const destRect = destEl.getBoundingClientRect();

            const x1 = srcRect.right - containerRect.left;
            const y1 = srcRect.top + srcRect.height / 2 - containerRect.top;

            const x2 = destRect.left - containerRect.left;
            // Determine vertical target position: upper half or lower half of next match card
            const isTopSlot = cIndex % 2 === 0;
            const y2 = isTopSlot
              ? destRect.top + destRect.height * 0.3 - containerRect.top
              : destRect.top + destRect.height * 0.7 - containerRect.top;

            // Draw smooth horizontal bezier curve
            const cp1x = x1 + (x2 - x1) * 0.5;
            const cp1y = y1;
            const cp2x = x1 + (x2 - x1) * 0.5;
            const cp2y = y2;

            const pathData = `M ${x1} ${y1} C ${cp1x} ${cp1y}, ${cp2x} ${cp2y}, ${x2} ${y2}`;

            // Path is active if source match is completed and winner progressed
            const active = match.status === 'COMPLETED' && 
                           (targetMatch.teamAId === match.winnerId || targetMatch.teamBId === match.winnerId);
            
            const isHovered = hoveredMatchId === match.id || hoveredMatchId === targetMatch.id;

            paths.push({ d: pathData, active, hovered: isHovered });
          }
        }
      });
    }

    // Draw line from Finals to Champion Card
    if (finalMatch) {
      const finalEl = containerRef.current?.querySelector(`#match-card-${finalMatch.id}`);
      const champEl = containerRef.current?.querySelector('#champion-card');

      if (finalEl && champEl) {
        const finalRect = finalEl.getBoundingClientRect();
        const champRect = champEl.getBoundingClientRect();

        const x1 = finalRect.right - containerRect.left;
        const y1 = finalRect.top + finalRect.height / 2 - containerRect.top;

        const x2 = champRect.left - containerRect.left;
        const y2 = champRect.top + champRect.height / 2 - containerRect.top;

        const cp1x = x1 + (x2 - x1) * 0.5;
        const cp1y = y1;
        const cp2x = x1 + (x2 - x1) * 0.5;
        const cp2y = y2;

        const pathData = `M ${x1} ${y1} C ${cp1x} ${cp1y}, ${cp2x} ${cp2y}, ${x2} ${y2}`;
        const active = finalMatch.status === 'COMPLETED';
        const isHovered = hoveredMatchId === finalMatch.id;

        paths.push({ d: pathData, active, hovered: isHovered });
      }
    }

    setSvgPaths(paths);
  };

  // Re-run path calculation on layout mount/resize
  useLayoutEffect(() => {
    updatePaths();
    
    // Resize Observer for robust measurement adjustments
    const resizeObserver = new ResizeObserver(() => {
      updatePaths();
    });
    if (containerRef.current) {
      resizeObserver.observe(containerRef.current);
    }

    // Set a tiny delayed update to ensure Next.js transitions/flex renders have settled
    const timeout = setTimeout(updatePaths, 150);

    return () => {
      resizeObserver.disconnect();
      clearTimeout(timeout);
    };
  }, [knockoutMatches.length, hoveredMatchId]);

  // Helper selectors
  function resolveTeam(tid: string) {
    if (!tid || tid === 'TBD') return 'TBD';
    return teamNameMap[tid] || tid.slice(0, 10) + '…';
  }

  function getScore(m: any, side: 'A' | 'B') {
    if (!m.resultSummary) return null;
    const rs = m.resultSummary as any;
    if (sport === 'FOOTBALL') {
      return side === 'A' ? rs.goalsA ?? null : rs.goalsB ?? null;
    }
    if (sport === 'CRICKET') {
      const runs = side === 'A' ? rs.runsA : rs.runsB;
      if (runs === undefined || runs === null) return null;
      const wickets = side === 'A' ? rs.wicketsA : rs.wicketsB;
      const w = wickets !== undefined && wickets !== null ? wickets : 0;
      return `${runs}/${w}`;
    }
    return null;
  }

  return (
    <div 
      ref={containerRef}
      className="relative flex items-stretch justify-between gap-16 py-8 overflow-x-auto min-w-[900px] w-full select-none"
    >
      {/* SVG Connections Overlay */}
      <svg className="absolute inset-0 pointer-events-none w-full h-full z-0">
        {svgPaths.map((path, idx) => (
          <path
            key={idx}
            d={path.d}
            fill="none"
            stroke={path.hovered ? '#fbbf24' : path.active ? '#10b981' : '#27272a'}
            strokeWidth={path.hovered ? 3 : path.active ? 2 : 1.5}
            className={`transition-all duration-300 ${
              path.hovered 
                ? 'drop-shadow-[0_0_8px_rgba(251,191,36,0.5)]' 
                : path.active 
                  ? 'drop-shadow-[0_0_6px_rgba(16,185,129,0.3)]' 
                  : ''
            }`}
          />
        ))}
      </svg>

      {/* Render Columns dynamically */}
      {stagesPresent.map((stage) => {
        const stageMatches = matchesByStage[stage] || [];
        return (
          <div key={stage} className="flex flex-col justify-around py-4 gap-12 flex-1 relative z-10">
            {/* Column Stage Header */}
            <div className="absolute top-0 left-1/2 -translate-x-1/2 text-[9px] font-black uppercase tracking-widest text-neutral-500 whitespace-nowrap bg-neutral-950 px-2.5 py-1 border border-white/5 rounded-full shadow-lg">
              {stageLabel[stage] || stage}
            </div>

            {stageMatches.map((m) => {
              const nameA = resolveTeam(m.teamAId);
              const nameB = resolveTeam(m.teamBId);
              const scoreA = getScore(m, 'A');
              const scoreB = getScore(m, 'B');
              const isLive = m.status === 'LIVE';
              const isDone = m.status === 'COMPLETED' || m.status === 'WALKOVER';
              const winnerIsA = isDone && m.winnerId === m.teamAId;
              const winnerIsB = isDone && m.winnerId === m.teamBId;

              const logoA = m.teamAId !== 'TBD' ? teamLogoMap[m.teamAId] : null;
              const logoB = m.teamBId !== 'TBD' ? teamLogoMap[m.teamBId] : null;

              return (
                <div
                  key={m.id}
                  id={`match-card-${m.id}`}
                  onMouseEnter={() => setHoveredMatchId(m.id)}
                  onMouseLeave={() => setHoveredMatchId(null)}
                  className={`w-52 shrink-0 bg-neutral-900 border rounded-2xl overflow-hidden transition-all duration-300 ${
                    isLive
                      ? 'border-red-500 shadow-[0_0_15px_rgba(239,68,68,0.2)] scale-[1.02]'
                      : hoveredMatchId === m.id
                        ? 'border-yellow-500 shadow-[0_0_15px_rgba(251,191,36,0.15)] scale-[1.01]'
                        : 'border-white/5 shadow-xl hover:border-white/10'
                  }`}
                >
                  {/* Match Number header */}
                  <div className="flex items-center justify-between px-3.5 py-1.5 bg-black/40 border-b border-white/5 text-[9px] font-black uppercase tracking-widest text-neutral-500">
                    <span>Match {m.matchNumber}</span>
                    {isLive && (
                      <span className="flex items-center gap-1 text-red-500 font-extrabold">
                        <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" /> LIVE
                      </span>
                    )}
                  </div>

                  {/* Team A Slot */}
                  <div className={`flex items-center justify-between px-4 py-2.5 border-b border-white/5 transition-all ${
                    winnerIsA ? 'bg-yellow-500/5' : isDone ? 'opacity-40' : ''
                  }`}>
                    <div className="flex items-center gap-2.5 min-w-0">
                      <div className="w-6 h-6 rounded-full bg-neutral-950 border border-white/10 flex items-center justify-center overflow-hidden shrink-0">
                        {logoA ? (
                          <img src={logoA} alt="" className="w-full h-full object-cover" />
                        ) : (
                          <Shield size={12} className="text-neutral-600" />
                        )}
                      </div>
                      <span className={`text-xs font-black truncate leading-none ${winnerIsA ? 'text-yellow-400 font-black' : 'text-neutral-200'}`}>
                        {nameA}
                      </span>
                    </div>
                    {scoreA !== null && (
                      <span className={`text-sm font-black font-mono leading-none ${winnerIsA ? 'text-yellow-400' : 'text-neutral-400'}`}>
                        {scoreA}
                      </span>
                    )}
                  </div>

                  {/* Team B Slot */}
                  <div className={`flex items-center justify-between px-4 py-2.5 transition-all ${
                    winnerIsB ? 'bg-yellow-500/5' : isDone ? 'opacity-40' : ''
                  }`}>
                    <div className="flex items-center gap-2.5 min-w-0">
                      <div className="w-6 h-6 rounded-full bg-neutral-950 border border-white/10 flex items-center justify-center overflow-hidden shrink-0">
                        {logoB ? (
                          <img src={logoB} alt="" className="w-full h-full object-cover" />
                        ) : (
                          <Shield size={12} className="text-neutral-600" />
                        )}
                      </div>
                      <span className={`text-xs font-black truncate leading-none ${winnerIsB ? 'text-yellow-400 font-black' : 'text-neutral-200'}`}>
                        {nameB}
                      </span>
                    </div>
                    {scoreB !== null && (
                      <span className={`text-sm font-black font-mono leading-none ${winnerIsB ? 'text-yellow-400' : 'text-neutral-400'}`}>
                        {scoreB}
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        );
      })}

      {/* Column 4: Champion Display Card */}
      <div className="flex flex-col justify-center py-4 flex-1 relative z-10">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 text-[9px] font-black uppercase tracking-widest text-neutral-500 whitespace-nowrap bg-neutral-950 px-2.5 py-1 border border-white/5 rounded-full shadow-lg">
          Champion
        </div>

        <div
          id="champion-card"
          className={`w-60 bg-gradient-to-br from-neutral-950 via-neutral-900 to-neutral-950 border rounded-3xl p-6 flex flex-col items-center text-center shadow-2xl transition-all duration-500 ${
            championId
              ? 'border-yellow-500/40 shadow-[0_0_30px_rgba(251,191,36,0.15)] scale-[1.02]'
              : 'border-white/5 opacity-40'
          }`}
        >
          {championId ? (
            <>
              {/* Trophy Icon Container */}
              <div className="w-16 h-16 rounded-full bg-yellow-500/10 border border-yellow-500/30 flex items-center justify-center text-yellow-400 mb-4 shadow-[0_0_15px_rgba(251,191,36,0.2)] animate-bounce duration-1000">
                <Trophy size={32} />
              </div>

              {/* Big Team Logo */}
              <div className="w-24 h-24 rounded-full bg-neutral-950 border-2 border-yellow-500/30 flex items-center justify-center overflow-hidden shadow-xl mb-4 relative p-1 group">
                <div className="absolute inset-0 bg-gradient-to-tr from-yellow-500/20 to-transparent animate-pulse rounded-full" />
                {teamLogoMap[championId] ? (
                  <img 
                    src={teamLogoMap[championId]} 
                    alt={teamNameMap[championId]} 
                    className="w-full h-full object-cover rounded-full z-10 group-hover:scale-110 transition-transform duration-500" 
                  />
                ) : (
                  <Shield size={48} className="text-yellow-500/60 z-10" />
                )}
              </div>

              {/* Champion Labels */}
              <h3 className="text-[10px] font-black uppercase tracking-widest text-yellow-500/80 mb-1">
                🏆 Champion 🏆
              </h3>
              <h2 className="text-lg font-black text-white leading-tight font-display tracking-tight break-words px-2 bg-gradient-to-r from-yellow-400 via-amber-200 to-yellow-500 bg-clip-text text-transparent drop-shadow-[0_2px_4px_rgba(0,0,0,0.5)]">
                {teamNameMap[championId]}
              </h2>
            </>
          ) : (
            <>
              <div className="w-16 h-16 rounded-full bg-neutral-900 border border-white/5 flex items-center justify-center text-neutral-700 mb-4">
                <Trophy size={32} />
              </div>
              <div className="w-24 h-24 rounded-full bg-neutral-950 border border-white/5 flex items-center justify-center mb-4">
                <Shield size={48} className="text-neutral-800" />
              </div>
              <h3 className="text-[10px] font-black uppercase tracking-widest text-neutral-600 mb-1">
                Undetermined
              </h3>
              <p className="text-xs text-neutral-500 font-bold px-4">
                Complete the tournament final match to reveal the champion.
              </p>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
